version: '3.4'

services:
  eventstore:
    image: eventstore/eventstore:20.10.0-buster-slim
    container_name: eventstore
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_EXT_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_DEV=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    networks:
      - ncafe
    logging:
      options:
        max-size: '100m'
        max-file: '5'
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9-management-alpine
    networks:
      - ncafe
    environment:
        - RABBITMQ_DEFAULT_USER=myuser
        - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
        - '5672:5672'
        - '15672:15672'
    volumes:
      - type: volume
        source: rabbitmq-volume-etc
        target: /etc/rabbitmq
      - type: volume
        source: rabbitmq-volume-data
        target: /var/lib/rabbitmq
      - type: volume
        source: rabbitmq-volume-logs
        target: /var/log/rabbitmq

networks:
  ncafe:
    name: ncafe

volumes:
  eventstore-volume-data:
    driver: local
  eventstore-volume-logs:
    driver: local
  rabbitmq-volume-etc:
    driver: local
  rabbitmq-volume-data:
    driver: local
  rabbitmq-volume-logs:
    driver: local
