services:
  admin:
    build:
      context: src/Admin/NCafe.Admin.Api/
    container_name: ncafe-admin
    restart: unless-stopped
    env_file: .env-local
    ports:
      - 5010:8080
    networks:
      - ncafe

  cashier:
    build:
      context: src/Cashier/NCafe.Cashier.Api/
    container_name: ncafe-cashier
    restart: unless-stopped
    env_file: .env-local
    ports:
      - 5020:8080
    networks:
      - ncafe

  barista:
    build:
      context: src/Barista/NCafe.Barista.Api/
    container_name: ncafe-barista
    restart: unless-stopped
    env_file: .env-local
    ports:
      - 5030:8080
    networks:
      - ncafe

  web-ui:
    build:
      context: src/UI/NCafe.Web/
    container_name: ncafe-ui
    restart: unless-stopped
    env_file: .env-local
    ports:
      - 5000:80
    networks:
      - ncafe

networks:
  ncafe:
    name: ncafe
