version: '3.4'

services:
  admin:
    build:
      dockerfile: src/Admin/NCafe.Admin.Api/Dockerfile
    container_name: ncafe-admin
    restart: unless-stopped
    env_file: .env-local
    ports:
      - 5010:80
    networks:
      - ncafe

  cashier:
    build:
      dockerfile: src/Cashier/NCafe.Cashier.Api/Dockerfile
    container_name: ncafe-cashier
    restart: unless-stopped
    env_file: .env-local
    ports:
      - 5020:80
    networks:
      - ncafe

  barista:
    build:
      dockerfile: src/Barista/NCafe.Barista.Api/Dockerfile
    container_name: ncafe-barista
    restart: unless-stopped
    env_file: .env-local
    ports:
      - 5030:80
    networks:
      - ncafe

networks:
  ncafe:
    name: ncafe
