name: ncafe-admin-api

ingress:
  enabled: true
  path: /admin
  hosts:
    - ncafe-dev.fredi.au

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 350m
    memory: 512Mi

environment:
  - name: ConnectionStrings__EventStore
    valueFromSecret: SecretKey

secrets:
  SecretKey: "{{CONNECTIONSTRINGS__EVENTSTORE}}"

replicaCount: 1
