name: ncafe-barista-api

ingress:
  enabled: true
  path: /barista
  hosts:
    - ncafe-dev.fredi.au

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 350m
    memory: 512Mi

environment:
  - name: ConnectionStrings__EventStore
    valueFromSecret: EventStoreConnectionString
  - name: ConnectionStrings__RabbitMq
    valueFromSecret: RabbitMqConnectionString

secrets:
  EventStoreConnectionString: "{{CONNECTIONSTRINGS__EVENTSTORE}}"
  RabbitMqConnectionString: "{{CONNECTIONSTRINGS__RABBITMQ}}"

replicaCount: 1
