name: ncafe-web-ui

ingress:
  enabled: true
  hosts:
    - ncafe-ui-dev.fredi.au

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 350m
    memory: 512Mi

environment:
  - name: ADMIN_BASE_ADDRESS
    value: "https://ncafe-dev.fredi.au/admin"
  - name: CASHIER_BASE_ADDRESS
    value: "https://ncafe-dev.fredi.au/cashier"
  - name: BARISTA_BASE_ADDRESS
    value: "https://ncafe-dev.fredi.au/barista"

replicaCount: 1
