name: Deploy to Kubernetes
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      namespace:
        required: true
        type: string
      project_folder:
        required: true
        type: string
    secrets:
      CONNECTIONSTRINGS__EVENTSTORE:
        required: true
      CONNECTIONSTRINGS__RABBITMQ:
        required: true
      KUBE_CONFIG:
        required: true

jobs:
  deploy:
    runs-on: self-hosted

    environment: ${{ inputs.environment }}

    env:
      CONNECTIONSTRINGS__EVENTSTORE: ${{ secrets.CONNECTIONSTRINGS__EVENTSTORE }}
      CONNECTIONSTRINGS__RABBITMQ: ${{ secrets.CONNECTIONSTRINGS__RABBITMQ }}

    steps:

    - uses: actions/checkout@v3

    - name: Download release artifacts
      uses: actions/download-artifact@v3
      with:
        name: release-artifacts
        path: ${{ inputs.project_folder }}/deploy/

    - uses: helmfile/helmfile-action@v1
      with:
        helmfile-version: 'v0.156.0'

    - name: Deploy to Kubernetes
      working-directory: ${{ inputs.project_folder }}
      run: |
        helmfile init --force
        sed -i "s/[$]namespace[$]/${{ inputs.namespace }}/g" deploy/helmfile.yaml
        echo -e "\e[92mConfiguring kubernetes access in pipeline...\e[0m"
        mkdir -p $(pwd)/.kube
        echo ${{ secrets.KUBE_CONFIG }} | base64 -d > $(pwd)/.kube/config
        export KUBECONFIG=$(pwd)/.kube/config
        echo -e "\e[92mDeploying to ${{ inputs.environment }} environment...\e[0m"
        cd deploy
        helmfile --color -e ${{ inputs.namespace }} apply --set image.imagePullPolicy=Always
